# project information
site_name: "Maker Hub"
site_author: "Stephen Eaton"
site_description: "Parts, Project builds and more for Makers"
site_url: https://madeinoz67.github.io/maker-hub/

# Page Tree
nav:
  - Home: index.md
  - User Guide:
    - ug/getting_started.md
    - ug/troubleshooting.md
  - Development:
      - dev/getting_started.md
      - dev/documentation.md
      - dev/makefile.md
      - Python: 
        - dev/python/python.md 
        - dev/python/database.md
      - dev/env.md
      - dev/docker.md
      - dev/contributing.md
  #- Reference:  # placeholder for API reference documentation
  - Contributors: authors.md
  - Change Log: changelog.md
  - License: license.md
  - Help Wanted: helpwanted.md

# Configuration
theme:
  favicon: img/favicon.ico
  logo: img/logo.svg
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - header.autohide

# Repository
repo_name: "madeinoz67/maker-hub"
repo_url: "https://github.com/madeinoz67/maker-hub"
google_analytics:
  - 'UA-190797511-2'
  - 'auto'

# plugins
plugins:
  - search
  - mermaid2

# extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.highlight
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji # noqa


      emoji_generator: !!python/name:materialx.emoji.to_svg # noqa


# Copyright
copyright: Copyright &copy; 2021 Stephen Eaton
# footer customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/madeinoz67"
    - icon: fontawesome/brands/gitlab
      link: "https://gitlab.com/madeinoz67"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/madeinoz"
