name: CI - Changelog

on:
  push:
    branches: [master]

jobs:
  changelog_prerelease:
    name: Update Changelog For Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: false
          unreleased: true
          addSections: '{"bugs": {"prefix": "[BUG]", "labels":["type: bug"]}, "features": {"prefix":"[FEATURE]", "labels":["type: enhancement"]},  "documentation":{"prefix":"[DOC]","labels":["type: documentation"]}, "dependencies": {"prefix": "Bump", "labels":["pr: dependencies"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for PR
          file_pattern: CHANGELOG.md
