name: Build Status

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          pip install poetry
          poetry install -D
      - run: cp .env.example .env
      # TODO: FastAPI migration
      # - name: Run Python lints
      #   run: pipenv run flask lint --check
      # - name: Run Python tests
      #   run: pipenv run flask test
